config/routes.rb
Rails.application.routes.draw do

  root 'portal#index'
  get 'portal/index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :shops do
    collection do
      get 'modal'
      post 'modal_create'
    end
  end

  resources :refills

  resources :toppings

  resources :tastes do
    collection do
      get 'modal'
      post 'modal_create'
    end
  end

  resources :ramen, shallow:true do
    resources :comments
    resources :likes
    collection do
      get ':taste_id/tastes' => 'ramen#tastes', as: :tastes
      get ':shop_id/shops' => 'ramen#shops', as: :shops
      get ':chain_shop_id/chain_shops' => 'ramen#chain_shops', as: :chain_shops
    end
    member do
      get 'get_image'
    end
  end

  get ':user_code' => 'users#ramen', as: :users_ramen
  get ':user_code/following' => 'users#following', as: :users_following
  get ':user_code/followers' => 'users#followers', as: :users_followers

end

app/models/chain_shop.rb
class ChainShop < ActiveRecord::Base
  has_many :ramen_shops, dependent: :destroy
  belongs_to :shop
  has_many :ramen, through: :ramen_shops
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ramen

  validates :body, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :ramen
end

app/models/ramen.rb
class Ramen < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  belongs_to :user#, class_name: "User"#, foreign_key: :user_code, primary_key: :code

  has_one :ramen_shop, dependent: :destroy
  has_one :shop, through: :ramen_shop
  accepts_nested_attributes_for :ramen_shop, reject_if: :all_blank
  has_one :chain_shop, through: :ramen_shop

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :ramen_tastes, dependent: :destroy
  has_many :tastes, through: :ramen_tastes
  accepts_nested_attributes_for :ramen_tastes, reject_if: :all_blank

  validates :name, presence: true
  validates :user_id, presence: true

  default_scope -> { order('created_at DESC') }
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM follows
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/ramen_shop.rb
class RamenShop < ActiveRecord::Base
  belongs_to :ramen
  belongs_to :shop
  belongs_to :chain_shop
end

app/models/ramen_taste.rb
class RamenTaste < ActiveRecord::Base
  belongs_to :ramen
  belongs_to :taste
end

app/models/refill.rb
class Refill < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :ramen_shops, dependent: :destroy
  has_many :chain_shops, dependent: :destroy
  has_many :ramen, through: :ramen_shops
end

app/models/taste.rb
class Taste < ActiveRecord::Base
  has_many :ramen_tastes, dependent: :destroy
  has_many :ramen, through: :ramen_tastes
end

app/models/topping.rb
class Topping < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ramen, class_name: "Ramen", dependent: :destroy#, foreign_key: :user_code, primary_key: :code
  has_many :likes, dependent: :destroy

  has_many :follower_relation, foreign_key: "follower_id", class_name: "Follow", dependent: :destroy
  has_many :followed_users, through: :follower_relation, source: :followed

  has_many :followed_relation, foreign_key: "followed_id", class_name: "Follow", dependent: :destroy
  has_many :followers, through: :followed_relation, source: :follower

  validates :code, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.from_omniauth(auth)
    # providerとuidでUserレコードを取得する
    # 存在しない場合は、ブロック内のコードを実行して作成する
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # auth.provider には "twitter"、
      # auth.uidには twitterアカウントに基づいた個別のIDが入っている
      # first_or_createメソッドが自動でproviderとuidを設定してくれるので、
      # ここでは設定は必要ない
      user.code = auth.info.nickname # twitterで利用している名前が入る
      user.name = auth.info.name # twitterで利用している名前が入る
      user.email = auth.info.email # twitterの場合入らない
      Rails.logger.info auth.info.inspect
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def email_required?
    (!provider || !email.blank?) && super
  end

  def password_required?
    super && provider.blank?
  end

  def following?(other_user)
    follower_relation.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    follower_relation.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    follower_relation.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @ramen = Ramen.find_by(id: params[:ramen_id])
    @comments = @ramen.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @ramen = Ramen.find_by(id: params[:ramen_id])
    @comment = @ramen.comments.build(comment_params)
    @comment.user_id = current_user.id

    logger.info @comment.inspect
    respond_to do |format|
      if @comment.save
        format.html { redirect_to ramen_url(@ramen.id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def shop_tag(item)
    shop = item.shop
    chain_shop = item.chain_shop
    content_tag :div, class: 'ramen-shop'
    if shop.present?
      body = shop_to(shop)
      if chain_shop.present?
        body += '('
        body += chain_shop_to(chain_shop)
        body += ')'
      end
    else
      body = content_tag :div, "どこかのお店", class: "shop-nothing"
    end
    body
  end

  def shop_to(shop)
    link_to shop.name, shops_ramen_index_path(shop.id), {class: ["ramen-shop-border", "marker"]}
  end

  def chain_shop_to(chain_shop)
    link_to chain_shop.name, chain_shops_ramen_index_path(chain_shop.id), {class: ["ramen-chain_shop-border", "marker"]}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/ramen_helper.rb
module RamenHelper
end

app/helpers/refills_helper.rb
module RefillsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, url: {controller: :comments, action: 'create', ramen_id: (@ramen ? @ramen.id : params[:ramen_id])} do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comments">
    <div class="comments-border">
      <div class="comments-profile">
        <%= image_tag "NCM_0561.JPG", {size: "30x30", class: "profile-img"} %>
        <div class="comments-profile-name">
          <div>
            <%= link_to current_user.name || current_user.code, users_ramen_path(current_user.code), {class: "user-name"} %>
            <%= "@#{current_user.code}" %>
          </div><br>
        </div>
        </div>
          <%= f.text_area :body, class: "comments-form" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="comments-main">
  <div class="ramen"><%= render partial: 'share/ramen', locals: {ramen: @ramen} %></div>

  <% @comments.each do |comment| %>
    <div class="comments">
      <div class="comments-border">
        <div class="comments-profile">
          <%= image_tag "NCM_0561.JPG", {size: "30x30", class: "profile-img"} %>
          <div class="comments-profile-name">
            <div>
              <%= link_to comment.user.name || comment.user.code, users_ramen_path(comment.user.code), {class: "user-name"} %>
              <%= "@#{comment.user.code}" %>
            </div>
            <div><%= "1時間前" %></div>
          </div>
        </div>
        <div class="comments-body"><%= comment.body %></div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Comment', new_ramen_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%#= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%#= link_to 'Back', comments_path %>