config/routes.rb
Rails.application.routes.draw do

  root 'portal#index'
  get 'portal/index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :shops do
    collection do
      get 'modal'
      post 'modal_create'
    end
  end

  resources :refills

  resources :toppings

  resources :tastes do
    collection do
      get 'modal'
      post 'modal_create'
    end
  end

  resources :ramen, shallow:true do
    resources :comments
    resources :likes
    collection do
      get ':taste_id/tastes' => 'ramen#tastes', as: :tastes
      get ':shop_id/shops' => 'ramen#shops', as: :shops
      get ':chain_shop_id/chain_shops' => 'ramen#chain_shops', as: :chain_shops
    end
    member do
      get 'get_image'
    end
  end

  get ':user_code' => 'users#ramen', as: :users_ramen
  get ':user_code/following' => 'users#following', as: :users_following
  get ':user_code/followers' => 'users#followers', as: :users_followers

end

app/models/ramen.rb
class Ramen < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  belongs_to :user#, class_name: "User"#, foreign_key: :user_code, primary_key: :code

  has_one :ramen_shop, dependent: :destroy
  has_one :shop, through: :ramen_shop
  accepts_nested_attributes_for :ramen_shop, reject_if: :all_blank
  has_one :chain_shop, through: :ramen_shop

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :ramen_tastes, dependent: :destroy
  has_many :tastes, through: :ramen_tastes
  accepts_nested_attributes_for :ramen_tastes, reject_if: :all_blank

  validates :name, presence: true
  validates :user_id, presence: true

  default_scope -> { order('created_at DESC') }
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM follows
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/ramen_controller.rb
class RamenController < ApplicationController
  before_action :set_ramen, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  # GET /ramen
  # GET /ramen.json
  def index
    @ramen = Ramen.all.includes([:ramen_tastes, :tastes, :ramen_shop, :shop])
  end

  def tastes
    taste = Taste.find_by(id: params[:taste_id])
    @ramen = taste.ramen
    render :index
  end

  def shops
    shop = Shop.find_by(id: params[:shop_id])
    @ramen = shop.ramen
    render :index
  end

  def chain_shops
    chain_shop = ChainShop.find_by(id: params[:chain_shop_id])
    @ramen = chain_shop.ramen
    render :index
  end

  def get_image
    @ramen = Ramen.find_by(id: params[:id])
  end

  # GET /ramen/1
  # GET /ramen/1.json
  def show
    @ramen = Ramen.find_by(id: params[:id])
    @comments = @ramen.comments
    @comment = Comment.new
  end

  # GET /ramen/new
  def new
    @ramen = Ramen.new
    @ramen.build_ramen_shop
    @ramen.ramen_tastes.build
  end

  # GET /ramen/1/edit
  def edit
  end

  # POST /ramen
  # POST /ramen.json
  def create
    @ramen = Ramen.new(ramen_params)
    @ramen.user_id = current_user.id

    p ramen_params
    p @ramen.ramen_tastes

    respond_to do |format|
      if @ramen.save
        format.html { redirect_to @ramen, notice: 'Ramen was successfully created.' }
        format.json { render :show, status: :created, location: @ramen }
      else
        format.html { render :new }
        format.json { render json: @ramen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ramen/1
  # PATCH/PUT /ramen/1.json
  def update
    respond_to do |format|
      if @ramen.update(ramen_params)
        format.html { redirect_to @ramen, notice: 'Ramen was successfully updated.' }
        format.json { render :show, status: :ok, location: @ramen }
      else
        format.html { render :edit }
        format.json { render json: @ramen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ramen/1
  # DELETE /ramen/1.json
  def destroy
    @ramen.destroy
    respond_to do |format|
      format.html { redirect_to ramen_url, notice: 'Ramen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ramen
      @ramen = Ramen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ramen_params
      params.require(:ramen).permit(:name, :picture, :body, :picture_cache, ramen_shop_attributes: [:id, :shop_id], ramen_tastes_attributes: [:id, :taste_id])
    end
end

app/helpers/ramen_helper.rb
module RamenHelper
end

app/views/ramen/_form.html.erb
<%= form_for(@ramen) do |f| %>
  <% if @ramen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ramen.errors.count, "error") %> prohibited this ramen from being saved:</h2>

      <ul>
      <% @ramen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="content">
    <div class="field">
      <%= "ラーメンの名前" %>
      <%= f.text_field :name %>
    </div>

    <%= f.fields_for :ramen_shop do |s| %>
      <div class="field">
        <%= "お店の名前" %>
        <%= link_to modal_shops_path, {remote: :ture, class: ["modal-open", "button-link"]} do %>
          <div class="select-link">
            <%= "選ぶ" %>
          </div>
        <% end %>
        <span id="select_shop"></span>
        <%= s.hidden_field :shop_id %>
      </div>
    <% end %>

    <div class="field">
      <%= "ラーメンの写真" %>
      <%= image_tag @ramen.picture if @ramen.picture? %>
        <div class="select-link">
          <%= "選ぶ" %>
          <%= f.file_field :picture, {class: "file-input"} %>
          <%= f.hidden_field :picture if @ramen.picture_cache %>
        </div>
        <div class="ramen-img">
          <%= image_tag "ramen.png" %>
        </div>
        <div class="file-name"></div>
    </div>

    <%= f.fields_for :ramen_tastes do |t| %>
      <div class="field">
        <%= "スープの味" %>
        <%= link_to modal_tastes_path, {remote: :ture, class: ["modal-open", "button-link"]} do %>
          <div class="select-link">
            <%= "選ぶ" %>
          </div>
        <% end %>
        <span id="select_tastes"></span>
        <div id="tastes-fields"><%= t.hidden_field :taste_id %></div>
      </div>
    <% end %>

    <div class="field">
      <%= "メモ" %>
      <%= f.text_area :body %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "食べた" %>
  </div>
<% end %>

<div id="modal-content">
  <div><a id="modal-close" class="button-link" onclick="hide_modal();">×</a></div>
  <div id="modal-body"></div>
</div>

<script type="text/javascript">
  $(".modal-open").click(function(){
    $(this).blur();
    if($("#modal-overlay")[0]) $("#modal-overlay").remove();
    //centeringModalSyncer();
  });

  function hide_modal(){
    $("#modal-content, #modal-overlay").fadeOut("slow",function(){
      $("#modal-overlay").remove();
      $("#modal-body").replaceWith('<div id="modal-body"></div>');
    });
  };

  function centeringModalSyncer(){
    //画面(ウィンドウ)の幅を取得し、変数[w]に格納
    var w = $(window).width();
    //画面(ウィンドウ)の高さを取得し、変数[h]に格納
    var h = $(window).height();
    //コンテンツ(#modal-content)の幅を取得し、変数[cw]に格納
    //var cw = $("#modal-content").outerWidth({margin:true});
    //コンテンツ(#modal-content)の高さを取得し、変数[ch]に格納
    //var ch = $("#modal-content").outerHeight({margin:true});
    var cw = $("#modal-content").width();
    var ch = $("#modal-content").height();
    //コンテンツ(#modal-content)を真ん中に配置するのに、左端から何ピクセル離せばいいか？を計算して、変数[pxleft]に格納
    var pxleft = ((w - cw)/2);
    //コンテンツ(#modal-content)を真ん中に配置するのに、上部から何ピクセル離せばいいか？を計算して、変数[pxtop]に格納
    var pxtop = ((h - ch)/2);
    //[#modal-content]のCSSに[left]の値(pxleft)を設定
    $("#modal-content").css({"left": pxleft + "px"});
    //[#modal-content]のCSSに[top]の値(pxtop)を設定
    //$("#modal-content").css({"top": pxtop + "px"});
    $("#modal-content").css({"top": "100px"});
  };

  $(function() {
    $('.file-input').on("change", function() {
      console.log(window.FileReader);
      var file = this.files[0];
      if(file != null) {
        console.log(file);
        $(".file-name").text(file.name);
      }
      fr = new FileReader();
      fr.onload = function() {
        return $(input).siblings("div").find("img").attr('src', fr.result);
      };
      return fr.readAsDataURL(file);
    });
  });
</script>

app/views/ramen/_ramen.html.erb
<% @ramen.each do |ramen| %>
  <li class="content">
    <h2 class="ramen-name"><%= ramen.name %></h2>
    <div class="ramen-shop"><%= shop_tag ramen %></div>
    <div><%= image_tag ramen.picture %></div>
    <% ramen.tastes.each do |taste| %>
      <span><%= link_to taste.name, tastes_ramen_index_path(taste.id), {class: "taste"} %></span>
    <% end %>
    <div class="profile">
      <%= image_tag "NCM_0561.JPG", {size: "40x40", class: "profile-img"} %>
      <div class="profile-name">
        <div>
          <%= link_to ramen.user.name, users_path(ramen.user.code), {class: "user-name"} %>
          <%= "さんがラーメンを食べました。" %>
        </div>
        <div><%= "1時間前" %></div>
      </div>
    </div>
  </li>
<% end %>

app/views/ramen/edit.html.erb
<h1>Editing Ramen</h1>

<%= render 'form' %>

<%= link_to 'Show', @ramen %> |
<%= link_to 'Back', ramen_path %>

app/views/ramen/get_image.js.erb
$("#ramen-img_<%= @ramen.id %>").html('<%= image_tag @ramen.picture %>');

app/views/ramen/index.html.erb
<p id="notice"><%= notice %></p>
<div class="main">
<% if false %>
  <ul style="list-style:none;">
    <% @ramen.each do |ramen| %>
      <li class="li-content"><%= render partial: 'share/ramen', locals: {ramen: ramen} %></li>
    <% end %>
  </ul>
<% else %>
  <% @ramen.each do |ramen| %>
    <%= render partial: 'share/ramen', locals: {ramen: ramen} %>
  <% end %>
<% end %>
</div>
<script type="text/javascript">
/*
  $(document).ready(function(){
    var ids = new Array();
    <% @ramen.each do |ramen| %>
      ids.push(<%= ramen.id %>);
    <% end %>
    $.each(ids, function(i, id) {
      $.ajax({
        url: "ramen/"+id+"/get_image",
        type: 'get',
        success: function(res) {
        },
        error: function(res, status) {
          alert("error!");
        }
      });
    });
  });
*/
</script>

app/views/ramen/new.html.erb
<h1>ラーメン食べた</h1>

<%= render 'form' %>

<%= link_to 'やっぱ食べてない', ramen_index_path %>

app/views/ramen/show.html.erb
<p id="notice"><%= notice %></p>

<div class="comments-main">
  <div class="ramen"><%= render partial: 'share/ramen', locals: {ramen: @ramen} %></div>

  <% @comments.each do |comment| %>
    <div class="comments">
      <div class="comments-border">
        <div class="comments-profile">
          <%= image_tag "NCM_0561.JPG", {size: "30x30", class: "profile-img"} %>
          <div class="comments-profile-name">
            <div>
              <%= link_to comment.user.name || comment.user.code, users_ramen_path(comment.user.code), {class: "user-name"} %>
              <%= "@#{comment.user.code}" %>
            </div>
            <div><%= "1時間前" %></div>
          </div>
        </div>
        <div class="comments-body"><%= comment.body %></div>
      </div>
    </div>
  <% end %>
</div>

<br>
<%= render partial: 'comments/form', locals: {comment: @comment} %>
<%#= link_to 'New Comment', new_ramen_comment_path(@ramen.id) %>